import type { OccasionDisposition } from "./contracts";

export const occasionDispositions: readonly OccasionDisposition[] = [
  {
    id: "occasion-birthday",
    sourceSlug: "birthday",
    currentLabel: "Birthday Party",
    intendedUserNeed: "Plan a private birthday yacht celebration",
    owningExistingPath: "/services/birthday-party",
    decision: "represented-by-existing-service-route",
    evidenceStatus: "confirmed",
    pageCreationApproved: false,
    notes: ["The /occasions hub should link to the existing service owner; no detail route is created."],
  },
  {
    id: "occasion-proposal",
    sourceSlug: "proposal",
    currentLabel: "Proposal",
    intendedUserNeed: "Plan a private yacht marriage proposal",
    owningExistingPath: "/services/marriage-proposal-party",
    decision: "represented-by-existing-service-route",
    evidenceStatus: "confirmed",
    pageCreationApproved: false,
    notes: ["The existing service candidate already represents this intent."],
  },
  {
    id: "occasion-corporate",
    sourceSlug: "corporate",
    currentLabel: "Corporate Event",
    intendedUserNeed: "Assess a private corporate yacht gathering",
    owningExistingPath: "/occasions",
    decision: "unsupported-pending-business-capability",
    evidenceStatus: "pending",
    pageCreationApproved: false,
    notes: ["Demand, capability, yacht selection, and optional services require evidence."],
  },
  {
    id: "occasion-fishing",
    sourceSlug: "fishing",
    currentLabel: "Fishing Trip",
    intendedUserNeed: "Plan a private fishing yacht experience",
    owningExistingPath: "/services/fishing",
    decision: "duplicate-of-existing-event-intent",
    evidenceStatus: "confirmed",
    pageCreationApproved: false,
    notes: ["Retain the occasion card only as a link to the existing service owner."],
  },
  {
    id: "occasion-sunset-cruise",
    sourceSlug: "sunset-cruise",
    currentLabel: "Sunset Cruise",
    intendedUserNeed: "Plan a private yacht experience around sunset",
    owningExistingPath: "/occasions",
    decision: "future-page-candidate-pending-evidence",
    evidenceStatus: "pending",
    pageCreationApproved: false,
    notes: ["Keep hub-only until route, demand, and operational facts are approved."],
  },
  {
    id: "occasion-new-year",
    sourceSlug: "new-year",
    currentLabel: "New Year's Eve",
    intendedUserNeed: "Assess a private New Year's Eve yacht request",
    owningExistingPath: "/occasions",
    decision: "unsupported-pending-business-capability",
    evidenceStatus: "pending",
    pageCreationApproved: false,
    notes: ["Seasonal availability, inclusions, duration, viewing, and hospitality claims are unverified."],
  },
  {
    id: "occasion-photoshoot",
    sourceSlug: "photoshoot",
    currentLabel: "Photoshoot",
    intendedUserNeed: "Assess a private yacht photoshoot request",
    owningExistingPath: "/occasions",
    decision: "represented-by-occasions-hub",
    evidenceStatus: "pending",
    pageCreationApproved: false,
    notes: ["Keep hub-only while supplier, drone, media, and capability evidence is missing."],
  },
];
